-- MySQL Script generated by MySQL Workbench
-- Wed Feb  2 10:27:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Reddit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Reddit` ;

-- -----------------------------------------------------
-- Schema Reddit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Reddit` ;
USE `Reddit` ;

-- -----------------------------------------------------
-- Table `Reddit`.`Subreddit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`Subreddit` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`Subreddit` (
  `subreddit_key` INT NOT NULL AUTO_INCREMENT,
  `subreddit_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `display_name` VARCHAR(50) NOT NULL,
  `display_name_prefixed` VARCHAR(50) NOT NULL,
  `title` TEXT NOT NULL,
  `url` TEXT NOT NULL,
  `created_utc` DATETIME NOT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `description_html` LONGTEXT NULL DEFAULT NULL,
  `public_description` LONGTEXT NULL DEFAULT NULL,
  `public_description_html` LONGTEXT NULL DEFAULT NULL,
  `submit_text` LONGTEXT NULL DEFAULT NULL,
  `submit_text_html` LONGTEXT NULL DEFAULT NULL,
  `submit_text_label` VARCHAR(100) NULL DEFAULT NULL,
  `accept_followers` TINYINT NULL DEFAULT NULL,
  `accounts_active` INT NULL DEFAULT NULL,
  `accounts_active_is_fuzzed` TINYINT NULL DEFAULT NULL,
  `active_user_count` INT NULL DEFAULT NULL,
  `all_original_content` TINYINT NULL DEFAULT NULL,
  `allow_discovery` TINYINT NULL DEFAULT NULL,
  `allow_galleries` TINYINT NULL DEFAULT NULL,
  `allow_images` TINYINT NULL DEFAULT NULL,
  `allow_polls` TINYINT NULL DEFAULT NULL,
  `allow_prediction_contributors` TINYINT NULL DEFAULT NULL,
  `allow_predictions` TINYINT NULL DEFAULT NULL,
  `allow_predictions_tournament` TINYINT NULL DEFAULT NULL,
  `allow_videogifs` TINYINT NULL DEFAULT NULL,
  `allow_videos` TINYINT NULL DEFAULT NULL,
  `can_assign_link_flair` TINYINT NULL DEFAULT NULL,
  `can_assign_user_flair` TINYINT NULL DEFAULT NULL,
  `collapse_deleted_comments` TINYINT NULL DEFAULT NULL,
  `comment_score_hide_mins` INT NULL DEFAULT NULL,
  `community_icon` TEXT NULL DEFAULT NULL,
  `community_reviewed` TINYINT NULL DEFAULT NULL,
  `disable_contributor_requests` TINYINT NULL DEFAULT NULL,
  `free_form_reports` TINYINT NULL DEFAULT NULL,
  `hide_ads` TINYINT NULL DEFAULT NULL,
  `icon_img` TEXT NULL DEFAULT NULL,
  `is_crosspostable_subreddit` TINYINT NULL DEFAULT NULL,
  `is_enrolled_in_new_modmail` TINYINT NULL DEFAULT NULL,
  `lang` VARCHAR(5) NULL DEFAULT NULL,
  `link_flair_enabled` TINYINT NULL DEFAULT NULL,
  `notification_level` VARCHAR(50) NULL DEFAULT NULL,
  `original_content_tag_enabled` TINYINT NULL DEFAULT NULL,
  `over18` TINYINT NULL DEFAULT NULL,
  `prediction_leaderboard_entry_type` VARCHAR(50) NULL DEFAULT NULL,
  `public_traffic` TINYINT NULL DEFAULT NULL,
  `quarantine` TINYINT NULL DEFAULT NULL,
  `restrict_commenting` TINYINT NULL DEFAULT NULL,
  `restrict_posting` TINYINT NULL DEFAULT NULL,
  `should_archive_posts` TINYINT NULL DEFAULT NULL,
  `show_media` TINYINT NULL DEFAULT NULL,
  `show_media_preview` TINYINT NULL DEFAULT NULL,
  `spoilers_enabled` TINYINT NULL DEFAULT NULL,
  `submission_type` VARCHAR(50) NULL DEFAULT NULL,
  `submit_link_label` VARCHAR(50) NULL DEFAULT NULL,
  `subreddit_type` VARCHAR(50) NULL DEFAULT NULL,
  `subscribers` INT NULL DEFAULT NULL,
  `suggested_comment_sort` VARCHAR(50) NULL DEFAULT NULL,
  `whitelist_status` VARCHAR(50) NULL DEFAULT NULL,
  `wiki_enabled` TINYINT NULL DEFAULT NULL,
  `wls` INT NULL DEFAULT NULL,
  PRIMARY KEY (`subreddit_key`),
  UNIQUE INDEX `subreddit_id_UNIQUE` (`subreddit_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reddit`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`User` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`User` (
  `user_key` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `created_utc` DATETIME NOT NULL,
  `subreddit` VARCHAR(50) NULL DEFAULT NULL,
  `accept_chats` TINYINT NULL DEFAULT NULL,
  `accept_followers` TINYINT NULL DEFAULT NULL,
  `accept_pms` TINYINT NULL DEFAULT NULL,
  `awardee_karma` INT NULL DEFAULT NULL,
  `awarder_karma` INT NULL DEFAULT NULL,
  `comment_karma` INT NULL DEFAULT NULL,
  `has_subscribed` TINYINT NULL DEFAULT NULL,
  `has_verified_email` TINYINT NULL DEFAULT NULL,
  `hide_from_robots` TINYINT NULL DEFAULT NULL,
  `icon_img` TEXT NULL DEFAULT NULL,
  `is_employee` TINYINT NULL DEFAULT NULL,
  `is_gold` TINYINT NULL DEFAULT NULL,
  `is_mod` TINYINT NULL DEFAULT NULL,
  `link_karma` INT NULL DEFAULT NULL,
  `pref_show_snoovatar` TINYINT NULL DEFAULT NULL,
  `snoovatar_img` TEXT NULL DEFAULT NULL,
  `total_karma` INT NULL DEFAULT NULL,
  `verified` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`user_key`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reddit`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`Post` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`Post` (
  `post_key` INT NOT NULL AUTO_INCREMENT,
  `post_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `user_key` INT NOT NULL,
  `user_id` VARCHAR(50) NOT NULL,
  `subreddit_key` INT NOT NULL,
  `subreddit_id` VARCHAR(50) NOT NULL,
  `parent_key` INT NULL DEFAULT NULL,
  `parent_id` VARCHAR(50) NULL DEFAULT NULL,
  `link_title` TEXT NULL DEFAULT NULL,
  `body` LONGTEXT NULL DEFAULT NULL,
  `body_html` LONGTEXT NULL DEFAULT NULL,
  `created_utc` DATETIME NOT NULL,
  `approved_at_utc` DATE NULL DEFAULT NULL,
  `approved_by` VARCHAR(50) NULL DEFAULT NULL,
  `archived` TINYINT NULL DEFAULT NULL,
  `banned_by` VARCHAR(50) NULL DEFAULT NULL,
  `banned_at_utc` DATETIME NULL DEFAULT NULL,
  `can_gild` TINYINT NULL DEFAULT NULL,
  `can_mod_post` TINYINT NULL DEFAULT NULL,
  `distinguished` VARCHAR(50) NULL DEFAULT NULL,
  `downs` INT NULL DEFAULT NULL,
  `edited` DATETIME NULL DEFAULT NULL,
  `gilded` INT NULL DEFAULT NULL,
  `locked` TINYINT NULL DEFAULT NULL,
  `mod_note` VARCHAR(100) NULL DEFAULT NULL,
  `mod_reason_by` VARCHAR(100) NULL DEFAULT NULL,
  `mod_reason_title` VARCHAR(100) NULL DEFAULT NULL,
  `no_follow` TINYINT NULL DEFAULT NULL,
  `num_reports` INT NULL DEFAULT NULL,
  `permalink` TEXT NULL DEFAULT NULL,
  `removal_reason` VARCHAR(100) NULL DEFAULT NULL,
  `report_reasons` VARCHAR(100) NULL DEFAULT NULL,
  `score` INT NULL DEFAULT NULL,
  `send_replies` TINYINT NULL DEFAULT NULL,
  `stickied` TINYINT NULL DEFAULT NULL,
  `top_awarded_type` VARCHAR(100) NULL DEFAULT NULL,
  `total_awards_received` INT NULL DEFAULT NULL,
  `ups` INT NULL DEFAULT NULL,
  `link_allow_live_comments` TINYINT NULL DEFAULT NULL,
  `link_category` VARCHAR(100) NULL DEFAULT NULL,
  `link_clicked` TINYINT NULL DEFAULT NULL,
  `link_comment_limit` INT NULL DEFAULT NULL,
  `link_comment_sort` VARCHAR(50) NULL DEFAULT NULL,
  `link_contest_mode` TINYINT NULL DEFAULT NULL,
  `link_content_categories` VARCHAR(100) NULL DEFAULT NULL,
  `link_discussion_type` VARCHAR(100) NULL DEFAULT NULL,
  `link_domain` VARCHAR(100) NULL DEFAULT NULL,
  `link_hidden` TINYINT NULL DEFAULT NULL,
  `link_hide_score` TINYINT NULL DEFAULT NULL,
  `link_is_crosspostable` TINYINT NULL DEFAULT NULL,
  `link_is_meta` TINYINT NULL DEFAULT NULL,
  `link_is_reddit_media_domain` TINYINT NULL DEFAULT NULL,
  `link_is_robot_indexable` TINYINT NULL DEFAULT NULL,
  `link_is_self` TINYINT NULL DEFAULT NULL,
  `link_is_video` TINYINT NULL DEFAULT NULL,
  `link_flair_text` TEXT NULL DEFAULT NULL,
  `link_flair_type` VARCHAR(50) NULL DEFAULT NULL,
  `link_media_only` TINYINT NULL DEFAULT NULL,
  `link_num_crossposts` INT NULL DEFAULT NULL,
  `link_num_comments` INT NULL DEFAULT NULL,
  `link_num_duplicates` INT NULL DEFAULT NULL,
  `link_over_18` TINYINT NULL DEFAULT NULL,
  `link_parent_whitelist_status` VARCHAR(50) NULL DEFAULT NULL,
  `link_pinned` TINYINT NULL DEFAULT NULL,
  `link_pwls` INT NULL DEFAULT NULL,
  `link_quarantine` TINYINT NULL DEFAULT NULL,
  `link_removed_by` VARCHAR(50) NULL DEFAULT NULL,
  `link_removed_by_category` VARCHAR(50) NULL DEFAULT NULL,
  `link_spoiler` TINYINT NULL DEFAULT NULL,
  `link_suggested_sort` VARCHAR(50) NULL DEFAULT NULL,
  `link_upvote_ratio` FLOAT NULL DEFAULT NULL,
  `link_url` TEXT NULL DEFAULT NULL,
  `link_view_count` INT NULL DEFAULT NULL,
  `link_visited` TINYINT NULL DEFAULT NULL,
  `link_whitelist_status` VARCHAR(50) NULL DEFAULT NULL,
  `link_wls` INT NULL DEFAULT NULL,
  `comment_collapsed` TINYINT NULL DEFAULT NULL,
  `comment_collapsed_because_crowd_control` VARCHAR(100) NULL DEFAULT NULL,
  `comment_collapsed_reason` VARCHAR(100) NULL DEFAULT NULL,
  `comment_collapsed_reason_code` VARCHAR(50) NULL DEFAULT NULL,
  `comment_controversiality` INT NULL DEFAULT NULL,
  `comment_depth` INT NULL,
  `comment_type` VARCHAR(50) NULL DEFAULT NULL,
  `comment_is_submitter` TINYINT NULL DEFAULT NULL,
  `comment_score_hidden` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`post_key`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`user_key`)
    REFERENCES `Reddit`.`User` (`user_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Post1`
    FOREIGN KEY (`parent_key`)
    REFERENCES `Reddit`.`Post` (`post_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Subreddit1`
    FOREIGN KEY (`subreddit_key`)
    REFERENCES `Reddit`.`Subreddit` (`subreddit_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reddit`.`Award`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`Award` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`Award` (
  `award_key` INT NOT NULL AUTO_INCREMENT,
  `award_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `award_sub_type` VARCHAR(50) NULL DEFAULT NULL,
  `award_type` VARCHAR(50) NULL DEFAULT NULL,
  `coin_price` INT NULL DEFAULT NULL,
  `coin_reward` INT NULL DEFAULT NULL,
  `subreddit_coin_reward` INT NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `icon_url` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`award_key`),
  UNIQUE INDEX `award_id_UNIQUE` (`award_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reddit`.`Post_has_award`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reddit`.`Post_has_award` ;

CREATE TABLE IF NOT EXISTS `Reddit`.`Post_has_award` (
  `post_key` INT NOT NULL,
  `award_key` INT NOT NULL,
  `post_id` VARCHAR(50) NOT NULL,
  `award_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`post_key`, `award_key`),
  CONSTRAINT `post_key`
    FOREIGN KEY (`post_key`)
    REFERENCES `Reddit`.`Post` (`post_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `award_key`
    FOREIGN KEY (`award_key`)
    REFERENCES `Reddit`.`Award` (`award_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
