from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Subreddit(Base):
    """
    Representa un subreddit.
    """
    __tablename__ = 'Subreddit'

    subreddit_key = Column(Integer, nullable=False, primary_key=True, autoincrement=True)
    subreddit_id = Column(String(50), nullable=False, unique=True)
    name = Column(String(50), nullable=False, unique=True)
    display_name = Column(String(50), nullable=False)
    display_name_prefixed = Column(String(50), nullable=False)
    title = Column(String(Text), nullable=False)
    url = Column(String(Text), nullable=False)
    created_utc = Column(DateTime, nullable=False)
    description = Column(Text)
    description_html = Column(Text)
    public_description = Column(Text)
    public_description_html = Column(Text)
    submit_text = Column(Text)
    submit_text_html = Column(Text)
    submit_text_label = Column(String(100))
    accept_followers = Column(Boolean)
    accounts_active = Column(Integer)
    accounts_active_is_fuzzed = Column(Boolean)
    active_user_count = Column(Integer)
    all_original_content = Column(Boolean)
    allow_discovery = Column(Boolean)
    allow_galleries = Column(Boolean)
    allow_images = Column(Boolean)
    allow_polls = Column(Boolean)
    allow_prediction_contributors = Column(Boolean)
    allow_predictions = Column(Boolean)
    allow_predictions_tournament = Column(Boolean)
    allow_videogifs = Column(Boolean)
    allow_videos = Column(Boolean)
    can_assign_link_flair = Column(Boolean)
    can_assign_user_flair = Column(Boolean)
    collapse_deleted_comments = Column(Boolean)
    comment_score_hide_mins = Column(Integer)
    community_icon = Column(Text)
    community_reviewed = Column(Boolean)
    disable_contributor_requests = Column(Boolean)
    free_form_reports = Column(Boolean)
    hide_ads = Column(Boolean)
    icon_img = Column(Text)
    is_crosspostable_subreddit = Column(Boolean)
    is_enrolled_in_new_modmail = Column(Boolean)
    lang = Column(String(5))
    link_flair_enabled = Column(Boolean)
    notification_level = Column(String(50))
    original_content_tag_enabled = Column(Boolean)
    over18 = Column(Boolean)
    prediction_leaderboard_entry_type = Column(String(50))
    public_traffic = Column(Boolean)
    quarantine = Column(Boolean)
    restrict_commenting = Column(Boolean)
    restrict_posting = Column(Boolean)
    should_archive_posts = Column(Boolean)
    show_media = Column(Boolean)
    show_media_preview = Column(Boolean)
    spoilers_enabled = Column(Boolean)
    submission_type = Column(String(50))
    submit_link_label = Column(String(50))
    subreddit_type = Column(String(50))
    subscribers = Column(Integer)
    suggested_comment_sort = Column(String(50))
    whitelist_status = Column(String(50))
    wiki_enabled = Column(Boolean)
    wls = Column(Integer)
